---
new_page_extension: md
auto_deploy: false
admin_path: site/static/admin
webhook_url: 
sections:
- type: directory
  path: site/content/page
  label: Page
  create: all
  match: "**/*"
- type: directory
  path: site/content/posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: site/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -s site
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  preview_output_directory: site/public
  output_directory: public
  instant_preview_command: hugo server -s site -D -E -F --port 8080 --bind 0.0.0.0
    --renderToDisk -d site/public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv/site"
version: 0.55.6
