baseurl = "https://morganj.co.uk/"
languageCode = "en"
title = "Jake Morgan"
theme = "hugo-paper"
googleAnalytics = ""
disqusShortname = ""
enableEmoji = true
Paginate = 3

# Syntax highlighting
pygmentsCodeFences = true
pygmentsOptions = "linenos=true"
pygmentsStyle = "perldoc"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[menu]
    [[menu.main]]
        name = "About"
        url = "/about-me/"
    [[menu.main]]
        name = "Blog"
        url = "/posts/"
    [[menu.main]]
        name = "GitHub"
        url = "https://github.com/jake-morgan/"

[params]
    description = ""

    # # Top left logo details
    # [params.logo]
    #     url = "logo.png"
    #     width = 50
    #     height = 50
    #     alt = "Logo"

    # # Favicon details
    # [params.icon]
    #     url = "pp.jpeg"
