baseurl = "https://jakemorgan.io/"
languageCode = "en"
title = "Jake Elliot Morgan"
theme = "lithium"
googleAnalytics = ""
disqusShortname = ""

# Syntax highlighting
pygmentsCodeFences = true
pygmentsOptions = "linenos=true"
pygmentsStyle = "perldoc"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[menu]
    [[menu.main]]
        name = "About"
        url = "/about-me/"
    [[menu.main]]
        name = "Posts"
        url = "/"
    [[menu.main]]
        name = "Github"
        url = "https://github.com/jake-morgan/"

[params]
    description = ""

    # Top left logo details
    [params.logo]
        url = "logo.png"
        width = 50
        height = 50
        alt = "Logo"

    # Favicon details
    [params.icon]
        url = "pp.jpeg"
